version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_PASSWORD: Talan
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: Heroes2

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Talan
    ports:
      - "5432:5432"
